#!/usr/bin/env python3
"""Generate preview.jpg — the card WhatsApp/iMessage/Slack show for the link.

Unlike ESPN, BBC, FotMob and the Premier League's own site — all of which share a
static logo — this one shows the CURRENT table, so a shared link carries real
football. Regenerated by the workflow on every data update.

Text stays large and short: these render as small thumbnails in chat.
"""
import io, json, urllib.request
from PIL import Image, ImageDraw, ImageFont

W, H = 1200, 630
PURPLE, DEEP, ACCENT = (61, 25, 91), (24, 12, 36), (201, 166, 255)
UA = {"User-Agent": "epl-tracker/1.0 (github.com/danpune/epl-tracker)"}


# macOS names first (local runs), then the fonts that ship on ubuntu-latest. Without
# the Linux paths every call fell through to load_default(), which IGNORES the size —
# CI was publishing a 1200x630 card with every string rendered at ~11px.
FONT_PATHS = {
    "Arial":       ["/System/Library/Fonts/Supplemental/Arial.ttf",
                    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
                    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"],
    "Arial Bold":  ["/System/Library/Fonts/Supplemental/Arial Bold.ttf",
                    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
                    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"],
    "Arial Black": ["/System/Library/Fonts/Supplemental/Arial Black.ttf",
                    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
                    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"],
}


def font(name, size):
    for path in FONT_PATHS[name]:
        try:
            return ImageFont.truetype(path, size)
        except OSError:
            continue
    # Fail loudly: load_default() would silently ship an unreadable card.
    raise SystemExit(f"no usable font for {name!r} — tried {FONT_PATHS[name]}")


def crest(url, px):
    """Club badge, transparency preserved. Returns None so a dead URL never breaks the build."""
    try:
        with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=20) as r:
            im = Image.open(io.BytesIO(r.read())).convert("RGBA")
        im.thumbnail((px, px), Image.LANCZOS)
        return im
    except Exception:
        return None


def main():
    d = json.load(open("data.json"))
    teams, table = d["teams"], d["table"]
    league = [m for m in d["matches"] if m["c"] == "PL"]
    played = sum(1 for m in league if m.get("done"))
    matchday = max([m.get("md", 0) for m in league if m.get("done")] or [0])

    img = Image.new("RGB", (W, H), PURPLE)
    dr = ImageDraw.Draw(img)
    for y in range(H):
        t = y / H
        dr.line([(0, y), (W, y)], fill=tuple(int(PURPLE[i] + (DEEP[i] - PURPLE[i]) * t) for i in range(3)))
    dr.ellipse([W - 300, H - 215, W + 240, H + 325], outline=(255, 255, 255), width=3)

    dr.text((64, 54), "PREMIER LEAGUE TRACKER", font=font("Arial Bold", 27), fill=ACCENT)
    dr.text((64, 96), f"{d['season']}  ·  Matchday {matchday}", font=font("Arial Black", 50), fill="white")

    # live table, top five — the part no other football site puts on its share card
    y = 210
    for r in table[:5]:
        t = teams[r["t"]]
        dr.text((64, y + 6), str(r["rank"]), font=font("Arial Bold", 30), fill=(150, 138, 166))
        c = crest(t.get("logo", ""), 40)
        if c:
            img.paste(c, (108, y - 2), c)
        dr.text((160, y + 2), t["short"][:18], font=font("Arial Bold", 34), fill="white")
        dr.text((556, y + 4), str(r["pld"]), font=font("Arial", 30), fill=(170, 158, 186))
        dr.text((620, y + 2), str(r["pts"]), font=font("Arial Black", 34), fill=ACCENT)
        y += 62

    dr.text((556, 176), "PL", font=font("Arial Bold", 21), fill=(150, 138, 166))
    dr.text((620, 176), "PTS", font=font("Arial Bold", 21), fill=(150, 138, 166))

    dr.text((760, 212), "Every kickoff", font=font("Arial Bold", 38), fill="white")
    dr.text((760, 258), "in YOUR", font=font("Arial Bold", 38), fill="white")
    dr.text((760, 304), "timezone.", font=font("Arial Bold", 38), fill=ACCENT)
    dr.text((760, 368), f"{played} of 380 played", font=font("Arial", 27), fill=(180, 168, 196))

    dr.rectangle([64, 540, 68, 584], fill=ACCENT)
    dr.text((86, 544), "Live scores · Highlights · Lineups · No ads",
            font=font("Arial Bold", 29), fill=(214, 202, 228))

    img.save("preview.jpg", "JPEG", quality=86, optimize=True)
    print(f"wrote preview.jpg — matchday {matchday}, top club {teams[table[0]['t']]['short']}")


if __name__ == "__main__":
    main()
