#!/usr/bin/env python3
"""Generate preview.jpg — the card WhatsApp/iMessage/Slack show for the link.

Unlike ESPN, BBC, FotMob and the Premier League's own site — all of which share a
static logo — this one shows the CURRENT table, so a shared link carries real
football. Regenerated by the workflow on every data update.

Text stays large and short: these render as small thumbnails in chat.
"""
import io, json, urllib.request
from datetime import datetime, timezone
from PIL import Image, ImageDraw, ImageFont

W, H = 1200, 630
FOLLOW = "manchesterunited"      # the club the card is addressed to
PURPLE, DEEP, ACCENT = (61, 25, 91), (24, 12, 36), (201, 166, 255)
UA = {"User-Agent": "epl-tracker/1.0 (github.com/danpune/epl-tracker)"}


# macOS names first (local runs), then the fonts that ship on ubuntu-latest. Without
# the Linux paths every call fell through to load_default(), which IGNORES the size —
# CI was publishing a 1200x630 card with every string rendered at ~11px.
FONT_PATHS = {
    "Arial":       ["/System/Library/Fonts/Supplemental/Arial.ttf",
                    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
                    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"],
    "Arial Bold":  ["/System/Library/Fonts/Supplemental/Arial Bold.ttf",
                    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
                    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"],
    "Arial Black": ["/System/Library/Fonts/Supplemental/Arial Black.ttf",
                    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
                    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"],
}


def font(name, size):
    for path in FONT_PATHS[name]:
        try:
            return ImageFont.truetype(path, size)
        except OSError:
            continue
    # Fail loudly: load_default() would silently ship an unreadable card.
    raise SystemExit(f"no usable font for {name!r} — tried {FONT_PATHS[name]}")


def club_base(team):
    """The club's colour, dark enough that white text sits on it.

    Every string on this card is white, and ESPN reports #ffffff as the primary for
    Spurs, Fulham and Leeds — so the same guard the site applies is applied here.
    """
    def rgb(h):
        h = str(h or "").lstrip("#")
        return [int(h[i:i + 2], 16) for i in (0, 2, 4)] if len(h) == 6 else None

    def lum(ch):
        v = [(x / 255) / 12.92 if x / 255 <= 0.03928 else (((x / 255) + 0.055) / 1.055) ** 2.4
             for x in ch]
        return 0.2126 * v[0] + 0.7152 * v[1] + 0.0722 * v[2]

    ch = rgb(team.get("col"))
    if not ch:
        return PURPLE
    for f in (1.0, 0.75, 0.55, 0.4, 0.3):
        cand = [round(x * f) for x in ch]
        if 1.05 / (lum(cand) + 0.05) >= 4.5:          # white text is legible on it
            return tuple(cand)
    return PURPLE


def crest(url, px):
    """Club badge, transparency preserved. Returns None so a dead URL never breaks the build."""
    try:
        with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=20) as r:
            im = Image.open(io.BytesIO(r.read())).convert("RGBA")
        im.thumbnail((px, px), Image.LANCZOS)
        return im
    except Exception:
        return None


def main():
    d = json.load(open("data.json"))
    teams, table = d["teams"], d["table"]
    league = [m for m in d["matches"] if m["c"] == "PL"]
    played = sum(1 for m in league if m.get("done"))

    # Lead with the club's next match, not the table. A fixture is what a fan taps a
    # link for; a table is a reference. FOLLOW is who the card is addressed to.
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%MZ")
    mine = sorted((m for m in d["matches"] if FOLLOW in (m["h"], m["a"])),
                  key=lambda m: m["utc"])
    nxt = next((m for m in mine if not m.get("done") and m["utc"] > now), None)
    last = next((m for m in reversed(mine) if m.get("done") and m.get("hs") is not None), None)

    base = club_base(teams.get(FOLLOW, {}))
    # a light tint of the club colour, so the accent belongs to the same card
    accent = tuple(round(c + (255 - c) * 0.68) for c in base)
    img = Image.new("RGB", (W, H), base)
    dr = ImageDraw.Draw(img)
    for y in range(H):
        t = y / H
        dr.line([(0, y), (W, y)], fill=tuple(int(base[i] + (DEEP[i] - base[i]) * t) for i in range(3)))
    dr.ellipse([W - 300, H - 215, W + 240, H + 325], outline=(255, 255, 255), width=3)

    dr.text((64, 52), "PREMIER LEAGUE TRACKER", font=font("Arial Bold", 26), fill=accent)

    if not nxt:                                   # season over, or no fixtures published
        dr.text((64, 104), "Premier League", font=font("Arial Black", 76), fill="white")
        dr.text((64, 190), "Tracker", font=font("Arial Black", 76), fill="white")
    else:
        comp = {"PL": "Premier League", "UCL": "Champions League",
                "FA": "FA Cup", "EFL": "EFL Cup"}.get(nxt.get("c", "PL"), "")
        md = f"  \u00b7  Matchday {nxt['md']}" if nxt.get("c") == "PL" and nxt.get("md") else ""
        dr.text((64, 100), (comp + md).upper(), font=font("Arial Bold", 24), fill=(168, 154, 186))

        # crest v crest, the two clubs stacked so long names never collide
        y = 148
        for side in (nxt["h"], nxt["a"]):
            t = teams[side]
            c = crest(t.get("logo", ""), 76)
            if c:
                img.paste(c, (64, y), c)
            bold = side == FOLLOW
            dr.text((156, y + 14), t["short"][:20],
                    font=font("Arial Black" if bold else "Arial Bold", 58),
                    fill="white" if bold else (214, 202, 228))
            if side == nxt["h"]:
                dr.text((64, y + 92), "v", font=font("Arial Bold", 26), fill=(150, 138, 166))
            y += 128

        ko = datetime.strptime(nxt["utc"], "%Y-%m-%dT%H:%MZ")
        where = "Home" if nxt["h"] == FOLLOW else "Away"
        dr.text((64, 428), ko.strftime("%a %d %b, %H:%M UK") + f"  \u00b7  {where}",
                font=font("Arial Bold", 33), fill=accent)
        dr.text((64, 474), "Kickoff shown in YOUR timezone on the site",
                font=font("Arial", 27), fill=(180, 168, 196))

    # right column: where the club sits, and the last result
    row = next((r for r in table if r["t"] == FOLLOW), None)
    if row:
        rank = row["rank"]
        suffix = "th" if 11 <= rank % 100 <= 13 else {1: "st", 2: "nd", 3: "rd"}.get(rank % 10, "th")
        dr.text((760, 148), str(rank), font=font("Arial Black", 66), fill="white")
        rw = dr.textlength(str(rank), font=font("Arial Black", 66))
        dr.text((760 + rw + 4, 168), suffix, font=font("Arial Bold", 30), fill=(190, 178, 205))
        dr.text((760, 228), "in the table", font=font("Arial Bold", 24), fill=(214, 202, 228))
        dr.text((760, 264), f"{row['pts']} pts \u00b7 {row['pld']} played",
                font=font("Arial Bold", 26), fill=(190, 178, 205))
    if last:
        opp = teams[last["a"] if last["h"] == FOLLOW else last["h"]]["short"]
        gf = last["hs"] if last["h"] == FOLLOW else last["as"]
        ga = last["as"] if last["h"] == FOLLOW else last["hs"]
        verb = "Won" if gf > ga else "Lost" if gf < ga else "Drew"
        dr.text((760, 336), "LAST TIME OUT", font=font("Arial Bold", 20), fill=(190, 178, 205))
        dr.text((760, 366), f"{verb} {gf}\u2013{ga}", font=font("Arial Black", 40), fill="white")
        dr.text((760, 418), "v " + opp[:16], font=font("Arial", 26), fill=(214, 202, 228))

    dr.rectangle([64, 540, 68, 584], fill=accent)
    dr.text((86, 544), f"Live scores \u00b7 Highlights \u00b7 {played} of 380 played",
            font=font("Arial Bold", 28), fill=(214, 202, 228))

    img.save("preview.jpg", "JPEG", quality=86, optimize=True)
    print(f"wrote preview.jpg \u2014 next: "
          + (f"{teams[nxt['h']]['short']} v {teams[nxt['a']]['short']}" if nxt else "no fixture"))


if __name__ == "__main__":
    main()
